#' Table of placebo output.
#' 
#'@description
#' `placebo_table()` Makes a summary table of estimated and placebo p values from output generated by 
#' [placebo()] or [placebo_im()].
#'
#' @param plbo An object created by [placebo()] or [placebo_im()].
#' @param caption An optional caption for the table.
#' 
#'
#' @return Generates a tinytable object. This gives the regression and placebo p values and the proportion
#' of placebo simulation significant at 5\% as the number of clusters increases.
#'  The regression confidence interval and its width are also reported. The next part of the table gives
#'  the z-score of a Moran test, using 5 nearest neighbours, the R2 of a regression of the treatment on the
#'  principal components of the tensor, and the effective range and structure of this regression's residuals.
#' @export
#'
#' @examples
#' library(spatInfer)
#' data(opportunity)
#' # Use 100 observations and 100 simulations to speed things up.
#' set.seed(123)
#' opportunity=opportunity |> dplyr::slice_sample(n=100)
#' # Use the number of splines and PCs indicated by [optimal_basis()] and turn off parallel processing.
#' plbo=placebo(mobility~single_mothers+short_commute+gini+dropout_rate+social_cap+dropout_na,                                 opportunity,
#' splines=6,
#' pc_num=15,
#' nSim=100,
#' Parallel=F,
#' max_clus = 7
#' )
#' placebo_table(plbo, caption="Placebo significance levels for single mothers variable.")


placebo_table=function(plbo, caption=""){
##plbo is output of `placebo()` or `placebo_im()` functions.

plbo$Results[3:5,1]=""

rr=plbo$Results|>
  dplyr::rename(Adj=SE) |> 
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,3)}))
ss=plbo$Spatial_Params|>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,2)}))

plac_tab=tinytable::tt(rr,theme="striped",align="r",digits=3,
              notes=   list(
                paste0("Moran=",ss$Moran,
                       ", Structure=",ss$Structure,
                       ", Effective Range=",ss$Effective_Range,
                       ", R2=",ss$R2,"."
                       ),
                paste0("Splines=",ss$Splines,
                       ", PCs=",ss$PCs,"."
                ),
                "Estimated and placebo p values and proportion of placebo regressions significant at 5%, along
                with confidence intervals. R2 gives the explanatory power of a regression of the treatment on the principal components."
              ),
              caption=caption
)

plac_tab= plac_tab |>
  tinytable::style_tt(i = 0, bold=T ) |>
  tinytable::style_tt(j=1, bold=T ) |>
  tinytable::style_tt(j = c("Plac 5%"), color = "orange")

return(plac_tab)
}
