#' Table of synthetic outcome significance levels.
#' 
#'@description
#' `synth_table()` Makes a summary table of estimated and placebo p values from output generated by 
#' [synth()] or [synth_im()].
#' 
#' @param syn An object containing simulation results created by synth or synth_im.
#' @param caption An optional caption for the table.
#'#'
#' @return Generates a tinytable object. This gives the regression and synthetic outcome p values as the number of clusters increases.
#'  The regression confidence interval and its width are also reported. The next part of the table gives
#'  the z-score of a Moran test, using 5 nearest neighbours, the R2 of a regression of the outcome on a
#'  quadratic in longitude and latitude, and the effective range and structure of this regression's residuals.
#' @export
#'
#' @examples
#' library(spatInfer)
#' data(opportunity)
#' # Use 100 observations and 100 simulations to speed things up.
#' set.seed(123)
#' opportunity=opportunity |> dplyr::slice_sample(n=100)
#' # Use the number of splines and PCs indicated by [optimal_basis()] and turn off parallel processing.
#' synt=synth(mobility~single_mothers+short_commute+gini+dropout_rate+social_cap+dropout_na,                                 opportunity,
#' splines=6,
#' pc_num=15,
#' nSim=100,
#' Parallel=F,
#' max_clus = 7
#' )
#' synth_table(synt, caption="Synthetic outcomes significance levels for single mothers variable.")


synth_table=function(syn, caption=""){
  
syn$Results[3:5,1]=""
rr=syn$Results
rr=rr |>
  dplyr::rename(Adj=SE) |> 
  dplyr::select(-dplyr::contains("_05"))|>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,3)}))
ss=syn$Spatial_Params
ss=ss |>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,2)}))

syn_tab=tinytable::tt(rr,theme="striped",align="r",digits=3 ,
              notes=   list(
                paste0("Moran=",ss$Moran,
                       ", Structure=",ss$Structure,
                       ", Effective Range=",ss$Effective_Range,
                       ", R2=",ss$R2,"."
                ),
                paste0(
                  "N=",ss$N,
                  ", Splines=",ss$Splines,
                       ", PCs=",ss$PCs,"."
                ),
                "Estimated and synthetic outcome p values for different cluster numbers.
                R2 gives the explanatory power of a regression of the outcome on a quadratic in longitude and latitude."
              ),
              caption=caption
)

syn_tab= syn_tab |>
  tinytable::style_tt(j = 1, bold=T )

return(syn_tab)
}
