#' Synthetic outcome tests using SCPC inference.
#'
#'@description
#' `synth_scpc()` runs synthetic outcome tests on regressions using SCPC
#' inference (Mueller and Watson) with increasing values of the average
#' correlation bound `avc` to test the null hypothesis that
#' the dependent variable is generated by a quadratic in longitude and latitude
#' plus noise and is therefore independent of the explanatory variable.
#'
#' @param fm  The equation formula. The variable of interest is the first one on
#'   the right hand side.
#' @param df  The name of the dataset use. Longitude and latitude must be named
#'   X and Y and have no missing values.
#' @param splines The dimension of the linear tensor used, from optimal_basis
#'   function
#' @param pc_num The number of principal component to include, again from
#'   optimal_basis
#' @param nSim The number of placebos to generate. Defaults to 1000 but lower
#'   values should be used first to get an idea of how the regression is
#'   behaving.
#' @param weights Set weights=TRUE if the regression is weighted. The weighting
#'   variable in the dataset must be named weights.
#' @param avc The values of the SCPC upper bound on the average pairwise
#'   correlation to examine. Each must lie between 0.001 and 0.99. Defaults to
#'   0.02, 0.04, 0.06, 0.08 and 0.1.
#' @param Parallel Run the simulations in parallel.
#' @param exact_cholesky For very large datasets, setting this to `FALSE` will
#'   use the BRISC Cholesky approximation. This requires the `BRISC` package.
#' @param jitter_coords If some sites have identical coordinates, jitter them for the
#'   Moran test by adding Gaussian noise with standard deviation 0.01 degrees
#'   (about 1 km). Set to `FALSE` to use the coordinates as they are, in which
#'   case spdep warns about identical points. Only the Moran test is affected.
#'
#' @details SCPC inference uses [scpcR::scpc()] with X and Y as longitude and
#'   latitude, so distances are great-circle distances. `Pseudo SE` is one
#'   quarter of the width of the 95% confidence interval, in the units of the
#'   treatment coefficient. A simulation where SCPC cannot be computed is left
#'   out, with a warning.
#'
#' @return Returns a list of synthetic outcome p values, spatial parameters,
#'   and Estimates giving the SCPC estimate, standard error, t statistic, p
#'   value and 95% confidence interval of the treatment for each value of `avc`.
#' @export
#'
#' @examples
#' library(spatInfer)
#' data(opportunity)
#' # Choose 100 observations and run simulations to speed things up.
#' set.seed(123)
#' opportunity=opportunity |> dplyr::slice_sample(n=100)
#' # Use the number of splines and PCs indicated by optimal_basis()
#' syn_scpc=synth_scpc(mobility~single_mothers+short_commute+gini+dropout_rate+social_cap,
#' opportunity,
#' splines=6,
#' pc_num=15,
#' nSim=100,
#' Parallel=FALSE
#' )
#'
#' synth_table(syn_scpc)


synth_scpc=function(fm,df,splines,pc_num,
                    nSim=1000,weights=FALSE,avc=seq(0.02,0.1,by=0.02),
                    Parallel=TRUE,exact_cholesky=TRUE,jitter_coords=TRUE){
#
  withr::local_preserve_seed()  #fixed simulation seeds do not change the user's random numbers
  avc=check_avc(avc)
  prep=prepare_spatial_data(fm,df,splines,pc_num,weights)
  df=prep$df
  rhs=prep$rhs
  pc=prep$pc
  rm(prep)


# Define two equations: the estimated equation using the true outcome variable and
# the simulated equation that uses paramaterized noise instead.
# Both equations have a spatial basis of principal components added.
eqs=build_formulas(rhs,pc,sim_replaces="dep_var")
eq_est=eqs$eq_est
eq_sim=eqs$eq_sim
rm(eqs)

# Regress dep_var on quadratic in long and lat to generate syn outcomes.
lm_res=lm(dep_var~poly(X,2)+poly(Y,2),
          data=df)

rm(pc)

# Get spatial correlation pattern of residuals and generate synth noise with the same structure.
noise_sim=Noise_Sim(df,lm_res,nSim,exact_cholesky,Parallel)
#Collect Output

#Moran test using 5 nearest neighbours
Moran=moran(eq_est,df,jitter_coords=jitter_coords)

Spatial_Params=data.frame(Moran,R2=summary(lm_res)$r.squared,   #explanatory power of quadratic for y
                          Effective_Range=noise_sim$matern_params$Effective_Range,   #fraction of 95th perc distance bw coords
                          Structure=noise_sim$matern_params$Structure)
Spatial_Params=round(Spatial_Params,3)
Spatial_Params=cbind.data.frame(Spatial_Params,N=nrow(df),Splines=splines,PCs=pc_num)
Sim=noise_sim$Sim
rm(noise_sim)

# Get p values of synth variables in simulated regressions both for SCPC and HC standard errors.
scpc_out=scpc_p_values(Sim,eq_sim,df,avc,nSim,Parallel)
hc_out=hc_p_values(Sim,eq_sim,df,nSim,Parallel)

# Summary synth results
summ=summary_scpc(df,eq_est,avc,scpc_out,hc_out)
Results=summ$Results |>
  dplyr::select(-sim_05)|>
  dplyr::rename(`Synth p`= sim_p,
                `Est p`=est_p,`CI Width`=width_ci,`Pseudo SE`=pseudo_se)

obj=list(
  Results=Results,
  Spatial_Params=Spatial_Params,
  Estimates=summ$Estimates
)
class(obj)=c("synth_scpc")
return(obj)

}
